# Generated by Django 5.0.3 on 2024-03-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='camp_register',
            field=models.BooleanField(default=False),
        ),
    ]
