# Generated by Django 5.0.3 on 2024-03-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_profile_camp_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='submitted_application',
            field=models.BooleanField(default=False),
        ),
    ]
