# Generated by Django 5.0.2 on 2024-03-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_skill_doctor_education_license_certification_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='aadhar_card',
        ),
        migrations.AddField(
            model_name='profile',
            name='aadhar_card_hashed',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
