# Generated by Django 5.0.3 on 2024-03-25 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_profile_submitted_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
