# Generated by Django 5.0.2 on 2024-03-05 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_remove_profile_aadhar_card_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='camp_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camp_name', models.CharField(max_length=200, null=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('lattitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('start_date_time', models.DateTimeField()),
                ('end_date_time', models.DateTimeField()),
                ('contact_website', models.URLField(blank=True, null=True)),
                ('hospital_name', models.CharField(blank=True, max_length=150, null=True)),
                ('club_name', models.CharField(blank=True, max_length=150, null=True)),
                ('other', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('type_of_camp', models.CharField(choices=[('Paid', 'Paid'), ('Free', 'Free')], max_length=30, null=True)),
                ('cost', models.IntegerField()),
                ('other_services', models.TextField(max_length=6000, null=True)),
                ('total_camp_registrations', models.IntegerField()),
            ],
        ),
    ]
