# Generated by Django 5.0.2 on 2024-03-08 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_camp_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp_details',
            name='cost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
