# Generated by Django 5.0.3 on 2024-03-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_camp_details_createdby'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp_details',
            name='camp_register_active',
            field=models.BooleanField(default=False),
        ),
    ]
