# Generated by Django 5.0.2 on 2024-03-08 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_alter_camp_details_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp_details',
            name='cost',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
